### ISSUE TITLE
July 2020 Meta-issue for Bugs

### ISSUE THREAD

**Issue by Crista2019** [NamelessChamber/NamelessChamber#66]
A list of existent bugs and weak points in the Nameless Chamber project:
- [ ]  Sixteenth note keystroke needs to be fixed
- [ ] Get rid of the sentences that pop up saying “measure 5 has too few/many beats” after hitting the “submit” button in any window.  But _keep_ the pop-ups that say the same message when user shifts to next measure.
- [ ] Have Help popup stay up until user clicks on it.

Stretch goals (not yet TODO):
- [ ] Checking for correct/incorrect notes needs to be by individual note so that if there are multiple incorrect (red) notes in a measure they don’t all turn back to black when only one note is corrected.  Right now the entire measure is rendered.
- [ ] Navigation menu doesn’t work when in rhythmic, melodic, harmonic pages.  In other words, if you are in the harmonic page and click on “go to melody” or “sign out” the page just scrolls down and nothing happens.  However, this is just on the student end.
- [ ] Be able to edit names of psets and courses and categories - right now have to delete the name and retype.
- [ ] Change to client-side so that the site doesn’t lag?
