### ISSUE TITLE
July 2020 Functionality Improvements Meta-Issue

### ISSUE THREAD

**Issue by Crista2019** [NamelessChamber/NamelessChamber#67]
FUNCTIONALITY GOALS
- [ ] Keystrokes for chromatics (maybe Shift+d = “do” for ascending etc. and Control+t = “teh” for descending etc.?) [Up/Down arrows already taken and + needs an extra key so those options won’t work)
- [ ] Have error popup if username/password is incorrect or registration key has expired.
- [ ] Add an Undo button
- [ ] Students receive an email saying their “final submit” has been received.

Stretch goals (not yet TODO)
- [ ] Minor psets changed to “do-based” minor.  In other words, do = tonic. But keep the current code that does “la-based” minor so that in the future we could have a button to toggle between the two systems.
- [ ] Octaves need to be reset to assigned default for the next note if the previous note was adjusted for octave by the user.
- [ ] Needs to follow accidental rules within a measure.
