### ISSUE TITLE
July 2020 Front-End Improvements Meta-Issue

### ISSUE THREAD

**Issue by Crista2019** [NamelessChamber/NamelessChamber#68]
FRONT END GOALS
- [ ] Larger audio box and in a convenient place where user/instructor doesn’t have to scroll page down to get to it.
- [ ] Scroll bar for the score in all views
- [ ] Rounded buttons, some shading, 3-D effects? Color schemes?

Stretch goals (not yet TODO)
- [ ] Get rid of program scrolling through options box when cursor passes notes in the score.
- [ ] Align notes between staves.
